<a href="https://colab.research.google.com/github/ianomwenga/PythonScripts/blob/main/BasicPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Check the version of pandas and numpy installed using the following commands: import numpy;print(numpy.version.version)#numpy version import pandas as pd;print(pd.version)#numpy version

```
# This is formatted as code
```



In [2]:
import numpy;
print (numpy.__version__)#numpy version

import pandas as pd;
print (pd.__version__)#pandas version

1.23.5
1.5.3


In [3]:
str = 'Helo HCIAPDTP-HuaweiTeam'
print(str)

Helo HCIAPDTP-HuaweiTeam


Write a program to define two variables, calculate their sum and display the results

In [4]:
x = 10 #defines variable named x
y = 5 #defines variable named y

z = x + y #defines a variable named z
print(z) #this prints the value of z


15


Write a program to define a tuple that contains only one element

In [5]:
colors = ("green", "purple", "beige", "brown")

Write a program to define a tuple and then use the 'for loop' to print all the elements using python

In [6]:
number = (1, 2, 3, 4, 5, 6, 7, 8, 9)
for item in number:
  print(item)

1
2
3
4
5
6
7
8
9


Write code to create a Python dictionary (the dict type) and print out the details. Add two entries to the dictionary: Associate the key 'name' with the value 'Reagan' and associate the key'phone' with '+254 722 222333'

In [7]:
my_dict = {"name": "Reagan", "phone": "+254722 222333"}
print(my_dict)

{'name': 'Reagan', 'phone': '+254722 222333'}


Define a function to do Multiplication, such as Mul(8,6), and it output 42

In [8]:
def Mul(x,y):
  return x * y
print(Mul(8,6))

48


Complete the function definition so it returns the square of the product of the parameters, so sqrProd(2,5) returns (2*5)*(2*5) = 100. def sqrPod(x,y):

In [9]:
def sqrProd(x, y):
  return (x * y) ** 2
print(sqrProd(2,5))

100


Import numpy and then:
(a) Use numpy to define an array, the shape of it is (5,5) and all elements of it is 0, using python

In [12]:
import numpy as np
array = np.zeros((5,5),dtype=int)
print(array)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


(b) Create a 3x3 matrix with values ranging from 0 t0 8 using python

In [14]:
import numpy as np
array = np.arange(9)
matrix = np.reshape(array,(3,3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


(c) Find indices of non-zero elements from [1,2,0,0,4,0]

In [15]:
import numpy as np
arr = np.array([1,2,0,0,4,0])
indices1 = np.nonzero(arr)
print(indices1)
indices2 = np.argwhere(arr)
print(indices2)

(array([0, 1, 4]),)
[[0]
 [1]
 [4]]


(d) Create a 10x10 array with random values and find the minimum and maximum values

In [36]:
import numpy as np
array = np.random.randint(low=1, high=100, size=(10,10))
print (array)

min_value = np.min(array)
max_value = np.max(array)

print("Minimum value:",min_value)
print("Maximum value:",max_value)

[[ 5 67 71 20 98 24 90 51 58 70]
 [67 20 44  1 36 84 22 49 61 62]
 [ 6 93 37 17 72 77  8  4 52  4]
 [79 63 40 82 22 99 23  5 17 60]
 [97 32 50 51  7 44 70  3 29 57]
 [15 31 46 29 70 20 32 84 80  7]
 [45 89 86 75 24 68 64 95 88 68]
 [35 20 10 97 53 78 45 32 53 60]
 [30 88 22 41 86 25 83 69 55 15]
 [ 9 37 95 81 40 48 39 23 31 32]]
Minimum value: 1
Maximum value: 99


(e) Create a random vector of size 30 and find the mean value

In [39]:
import numpy as np
vector = np.random.randint(low=1, high=100, size=(30))
mean = np.mean (vector)
print ("Vector:", vector)
print ("Mean:", mean)

Vector: [83 98 48 71 37 73 11 69 22 40 59 75 18 12 17 20 75 35 98 28 38 73 15 42
 14  4 68 61 66 43]
Mean: 47.1


Write a python program that prompts the user for two numbers, read them in, and prints out the product, labelled appropriately.


In [40]:
num1 = input ("Enter the first number: ")
num2 = input ("Enter the second number:")

num1 = int (num1)
num2 = int (num2)

product = num1 * num2

print ("The product of the two numbers is:", product)

Enter the first number: 7
Enter the second number:9
The product of the two numbers is: 63


Complete the code for the following function so it matches its documentation:def doubleList(numberList): For each of the numbers in the list numberList, print a line containing twice the original number. For example, doubleList ([3,1,5]) would print 6,2,10

In [42]:
def doubleList (numberList):
  for num in numberList:
    print(num * 2)
doubleList([3,1,5])

6
2
10
